### ISSUE TITLE
Crash with JobGlassFactory

### ISSUE THREAD

**Issue by fabbe50** [TheResimulators/Sim-U-Kraft-Resimulated-1.15#131]
See crash report attached.

[crash-2023-07-26_15.29.11-server.txt](https://github.com/TheResimulators/Sim-U-Kraft-Resimulated-1.16/files/12172988/crash-2023-07-26_15.29.11-server.txt)

**Comment by aidie8** [comment]
what is the steps to reproduce?

**Comment by fabbe50** [comment]
Build Grocery Store.
Hire Sim as Glass Factory (apparently).
Let Sim work for a while.
Crash.

**Comment by aidie8** [comment]
Ah ok. That's why, the grocery store has the wrong job assigned to it, causing it to look for a furnace when there is no, that does raise an underlying issue with the glass factory though.
In the professions class, grocer has glassfactory as it tileentity I think. Or it's modJobs class

**Comment by aidie8** [comment]
Created a temporary AI and GUI for the Grocerer to fix this issue
