### ISSUE TITLE
Sim Info GUI

### ISSUE THREAD

**Issue by Reprevise** [TheResimulators/Sim-U-Kraft-Resimulated-1.15#20]
This issue is to track our progress on the Sim Info GUI.

**Comment by fabbe50** [comment]
What does this GUI include? I assume it's different from the individual Sims info GUI? Like health and stuff?

**Comment by aidie8** [comment]
I think We good add this to the custom labels rendering. like have options e.g
for hunger
Well Fed
Little hungry
Peckish
Hungry
Starving. depending on what it is
health would be similar as well. and then have the sim gui that shows. there name,age,job, etc in detail

**Comment by fabbe50** [comment]
Alright... so I shouldn't put Health, Hunger and Armor in the Inventory GUI?

**Comment by fabbe50** [comment]
I thought the labels were for what the Sim was thinking about though.
