### ISSUE TITLE
Miner AI

### ISSUE THREAD

**Issue by Reprevise** [TheResimulators/Sim-U-Kraft-Resimulated-1.15#22]
This issue is to track our progress on the Miner AI.

With the miner AI, there are two ways we can define the area:
1. Like the original mod, we could use a land marker to lay out an area that can be used. The landmarks could have other uses as well like a marker for outlining an area for the lumberjacks.
2. We do it all through a GUI, making a radius and depth input and a toggle for rendering the outline.

Let me know what you guys think and if there is a different way that we could do it.

**Comment by basmulder03** [comment]
I think method 1 is the most user friendly

**Comment by general5001** [comment]
i also like option 1

**Comment by Reprevise** [comment]
I think we should do option one, for ease of use and out of respect for the original mod.
