### ISSUE TITLE
No sims on reload

### ISSUE THREAD

**Issue by Reprevise** [TheResimulators/Sim-U-Kraft-Resimulated-1.15#49]
## Error:
```
[ne.mi.fm.ne.si.IndexedMessageCodec/SIMPLENET]: Received empty payload on channel fml:handshake
```

## Steps to reproduce:

1. Have Sims spawn in the world while you're there
3. Notice the Sims are there
4. Save and exit the world
5. Reload the world
7. No Sims are present on the screen and the aforementioned error is shown

**Comment by aidie8** [comment]
Does the Hud stay updated though.
if there is 5 sims before saving. after loading does the Hud still say 5

**Comment by Reprevise** [comment]
Yes, the UI stays updated @aidie8.

**Comment by fabbe50** [comment]
The Sims don't even persist in the world after reload. At least not the ones spawning through spawn eggs.

**Comment by Reprevise** [comment]
But the ones that spawn in the new day persist for you right, @fabbe50?

**Comment by fabbe50** [comment]
No, they don't. Not even in a newly generated world. The UI keeps the number but there's no Sims.
Something wrong with the net code I assume, getting this in the console on world load: 
> [ne.mi.fm.ne.si.IndexedMessageCodec/SIMPLENET]: Received empty payload on channel fml:handshake

**Comment by fabbe50** [comment]
Once for every Sim loaded into the world.

**Comment by Reprevise** [comment]
Yep I can get the same error.

**Comment by aidie8** [comment]
i'll look into it today when i have a free minute

**Comment by aidie8** [comment]
![image](https://user-images.githubusercontent.com/13826618/75093054-53cb7000-55e3-11ea-88b2-a61f3edc1b70.png)
I don't think that is related at least on mine it only does it twice. its a handshake so that like core forge i think
