### ISSUE TITLE
Sim Names

### ISSUE THREAD

**Issue by aidie8** [TheResimulators/Sim-U-Kraft-Resimulated-1.15#61]
Added randomly generated names depending on gender

**Comment by fabbe50** [comment]
This randomization already exists except when you spawn them through new day. How are you doing the spawning? They get a random name both through the spawn egg and through the summon command (as far as I know).

**Comment by aidie8** [comment]
Doing it through an event when it's a new day. Just using something like "world.SpawnEntity(new simEntity()) "

**Comment by fabbe50** [comment]
Somehow that must skip the "createEntity" bit... that's interesting.

**Comment by aidie8** [comment]
going to fix this now

**Comment by aidie8** [comment]
it uses addEntity so it might be the wrong method

**Comment by fabbe50** [comment]
No idea... the names are added in the onInitialSpawn method in the SimEntity class

**Comment by aidie8** [comment]
Fixed it. just had to call that method after spawning the sim in the event

**Comment by fabbe50** [comment]
Right
